### ISSUE TITLE
Z-Machine Bug

### ISSUE THREAD

**Issue by tomvdb** [eschalks/zmachine-csharp#1]
Hi,

Not sure if this project is still active. I managed to incorporate it into my project, but it seems like the z-machine crashes on certain actions in Zork1 :(

Machine.next() throws exception: 1OP:9 @ 78CC

This happens every time I try to eat garlic found in the sack in the house :)

**Comment by eschalks** [comment]
Hey,

Thanks for the bug report. 
It's always nice to discover I'm not the only person using my code :smile:

This problem has been fixed in commit 52b5662.
You can now eat all the lunches and garlic you desire.

**Comment by tomvdb** [comment]
Awesome thanks, works great :) Having lots of fun with your z-machine. Turned it into a telegram bot. Lots of fun :)
